=== ZsZs/ProcessPuzzleFramework/Implementation/DomainTier/Source/com/processpuzzle/business/definition/domain/BusinessDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema 
	targetNamespace = "http://www.processpuzzle.com/"
	elementFormDefault = "qualified" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://www.processpuzzle.com/">

	<xsd:element name="businessDefinition">
		<xsd:complexType>
			<xsd:sequence maxOccurs="1">
				<xsd:element name="partyTypes" type="PartyTypes" minOccurs="0"></xsd:element>
				<xsd:element name="partyRoleTypes" type="PartyRoleTypes" minOccurs="0"></xsd:element>
				<xsd:element name="partyRelationshipTypes" type="PartyRelationshipTypes" minOccurs="0"></xsd:element>
				<xsd:element name="artifactTypes" type="ArtifactTypeListDefinition" minOccurs="0"></xsd:element>
				<xsd:element name="protocols" type="ProtocolListDefinition" minOccurs="0"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- ProtocolDefinition Begin -->

	<xsd:complexType name="ProtocolListDefinition">
		<xsd:sequence minOccurs="1" maxOccurs="1">
			<xsd:element name="activities" type="ActivityListDefinition" />
			<xsd:element name="workflowDetails" type="WorkflowDetailListDefinition" />
			<xsd:element name="lifecycleProtocol" type="LifeCycleProtocolType" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ActivityListDefinition">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="activity" type="ActivityProtocolListDefinitionType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ActivityProtocolListDefinitionType">
		<xsd:attribute name="name" type="xsd:ID" use="required" />
		<xsd:attribute name="performerRole" type="xsd:IDREF" use="required" />
	</xsd:complexType>

	<xsd:complexType name="WorkflowDetailListDefinition">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="workflowDetail" type="WorkflowDetailProtocolType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="WorkflowDetailProtocolType">
		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="activity" type="xsd:IDREF"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="LifeCycleProtocolType">
		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="lifecyclePhase" type="LifeCyclePhaseProtocolType" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="prefix" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="LifeCyclePhaseProtocolType">
		<xsd:choice minOccurs="0" maxOccurs="unbounded" >
			<xsd:element name="workflowDetail" type="WorkflowDetailProtocolType" minOccurs="0" />
			<xsd:element name="activity" type="xsd:IDREF" minOccurs="0"/>
		</xsd:choice>
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>
	<!-- ProtocolDefinition End -->

	<!-- PartyType Begin -->
	<xsd:complexType name = "PartyTypes">
		<xsd:sequence minOccurs = "0" maxOccurs = "unbounded">
			<xsd:element name = "partyType" type = "PartyType" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="PartyType">
		<xsd:sequence minOccurs="0" maxOccurs = "1">
			<xsd:element name="description" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:ID" use="required" />
		<xsd:attribute name="partyClassName" type="xsd:string" />
	</xsd:complexType>
	
	<!-- PartyRoleTypeDefinition Begin -->
	<xsd:complexType name="PartyRoleTypes">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="partyRoleType" type="PartyRoleType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="PartyRoleType">
		<xsd:sequence minOccurs="0" maxOccurs="1">
			<xsd:element name="description" type="xsd:string" />
			<xsd:element name="partyRoleConstraints">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="partyRoleConstraint" type="PartyRoleConstraint" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:ID" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="PartyRoleConstraint">
		<xsd:attribute name="typeOfParty" type="xsd:IDREF"  use="required" />
	</xsd:complexType>

	<xsd:complexType name="PartyRelationshipTypes">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="partyRelationshipType" type="PartyRelationshipType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="PartyRelationshipType">
		<xsd:sequence minOccurs="0" maxOccurs="1">
			<xsd:element name="partyRelationshipConstraints">
				<xsd:complexType>
					<xsd:sequence minOccurs="1" maxOccurs="unbounded">
						<xsd:element name="partyRelationshipConstraint" type="PartyRelationshipConstraint" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:token" />
	</xsd:complexType>

	<xsd:complexType name="PartyRelationshipConstraint">
		<xsd:attribute name="clientRoleType" type="xsd:token" use="required" />
		<xsd:attribute name="supplierRoleType" type="xsd:token" use="required" />
	</xsd:complexType>

	<!-- ArtifactTypeListDefinition Begin -->

	<xsd:complexType name="ArtifactTypeListDefinition">
		<xsd:sequence minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="artifactTypeGroup">
				<xsd:complexType>
					<xsd:sequence minOccurs="1" maxOccurs="1">
						<xsd:element name="defaultAccessRights" type="AccessRightsList" minOccurs="0" maxOccurs="1" />
						<xsd:sequence minOccurs="0" maxOccurs="unbounded">
							<xsd:element name="artifactType" type="ArtifactTypeDefinition"></xsd:element>
						</xsd:sequence>
					</xsd:sequence>
					<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ArtifactTypeDefinition">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="caption" type="xsd:string"></xsd:element>
			<xsd:element name="baseUri" type="xsd:string"></xsd:element>
			<xsd:element name="defaultAccessRights" type="AccessRightsList" minOccurs="0" maxOccurs="1" />
			<xsd:element name="creationProperties" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence minOccurs="1" maxOccurs="unbounded">
						<xsd:element name="creationProperty" type="PropertyDefinition"></xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="availableViews" maxOccurs="unbounded" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:choice>
							<xsd:element name="propertyViewType" type="PropertyViewType"></xsd:element>
							<xsd:element name="printViewType" type="PrintViewType"></xsd:element>
							<xsd:element name="editableTextViewType" type="EditableTextViewType"></xsd:element>
							<xsd:element name="artifactListViewType" type="ArtifactListViewType"></xsd:element>
							<xsd:element name="artifactModificationsViewType" type="ArtifactModificationsViewType"></xsd:element>
							<xsd:element name="relatedArtifactsViewType" type="RelatedArtifactsViewType"></xsd:element>
							<xsd:element name="artifactCommentsViewType" type="ArtifactCommentsViewType"></xsd:element>
							<xsd:element name="accessRightsViewType" type="AccessRightsViewType"></xsd:element>
							<xsd:element name="artifactCustomFormViewType" type="ArtifactCustomFormViewType"></xsd:element>
							<xsd:element name="listQueryViewType" type="ListQueryViewType"></xsd:element>
						</xsd:choice>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="associatedMenuItems" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="menuItem" type="MenuItemDefinition"></xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:ID" use="required"></xsd:attribute>
		<xsd:attribute name="group" type="xsd:token" use="required"></xsd:attribute>
		<xsd:attribute name="artifactClassName" type="xsd:token" use="required"></xsd:attribute>
		<xsd:attribute name="domainClassName" type="xsd:token"></xsd:attribute>
		<xsd:attribute name="instanceFolder" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="pessimisticLock" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
		<xsd:attribute name="isSystem" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
		<xsd:attribute name="isVersionControlled" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
		<xsd:attribute name="createOnStartUp" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
		<xsd:attribute name="isSingleton" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
		<xsd:attribute name="refreshOnDocumentActivation" type="xsd:boolean" default="false"></xsd:attribute>
		<xsd:attribute name="refreshOnViewActivation" type="xsd:boolean" default="false"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="ArtifactViewType">
		<xsd:sequence>
			<xsd:element name="viewCaption" type="xsd:string" />
			<xsd:element name="viewAccessUrl" type="xsd:string" minOccurs="0" maxOccurs="1" />
			<xsd:element name="associatedMenuItems" maxOccurs="unbounded" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="menuItem" type="MenuItemDefinition"></xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
		<xsd:attribute name="clientType" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:token">
					<xsd:enumeration value="PropertyView"></xsd:enumeration>
					<xsd:enumeration value="NativeView"></xsd:enumeration>
					<xsd:enumeration value="BrowseView"></xsd:enumeration>
					<xsd:enumeration value="PrintView"></xsd:enumeration>
					<xsd:enumeration value="EditableHtmlView"></xsd:enumeration>
					<xsd:enumeration value="CustomFormView"></xsd:enumeration>
					<xsd:enumeration value="ListQueryView"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="presentationUri" type="xsd:token" use="optional"></xsd:attribute>
		<xsd:attribute name="viewClassName" type="xsd:token" use="optional"></xsd:attribute>
		<xsd:attribute name="isDefault" type="xsd:boolean" default="false" use="optional" />
		<xsd:attribute name="isStatic" type="xsd:boolean" default="true" use="optional" />
	</xsd:complexType>

	<!-- ViewType extensions - begin -->
	<xsd:complexType name="PropertyViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PrintViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType">
				<xsd:attribute name="xmlToFoXsltPath" type="xsd:token" use="required"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="EditableTextViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType">
				<xsd:attribute name="xmlToHtmlXsltPath" type="xsd:token" use="required"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ArtifactListViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType">
				<xsd:attribute name="listedArtifactType" type="xsd:token" use="required"></xsd:attribute>
				<xsd:attribute name="orderBy" type="xsd:token" use="optional"></xsd:attribute>
				<xsd:attribute name="order" type="SortOrder" use="optional"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ListQueryViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType">
				<xsd:sequence>
					<xsd:element name="preDefinedQueries" maxOccurs="1" minOccurs="0">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="query" minOccurs="1" maxOccurs="unbounded">
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element name="description" type="xsd:string"></xsd:element>
											<xsd:element name="statement" type="xsd:string"></xsd:element>
										</xsd:sequence>
										<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="targetPropertyView" type="xsd:token" use="required" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ArtifactModificationsViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="RelatedArtifactsViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ArtifactCommentsViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="AccessRightsViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ArtifactCustomFormViewType">
		<xsd:complexContent>
			<xsd:extension base="ArtifactViewType"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- ViewType extensions - end -->

	<xsd:complexType name="MenuItemDefinition">
		<xsd:sequence>
			<xsd:element name="command" type="WebUICommandDefinition" minOccurs="0" maxOccurs="1"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="PropertyDefinition">
		<xsd:sequence minOccurs="0" maxOccurs="1">
			<xsd:element name="defaultValue" ></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:token" use="required"></xsd:attribute>
		<xsd:attribute name="type" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:token">
					<xsd:enumeration value="string"></xsd:enumeration>
					<xsd:enumeration value="integer"></xsd:enumeration>
					<xsd:enumeration value="date"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:simpleType name="ViewTypeName">
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="ArtifactPropertyViewType"></xsd:enumeration>
			<xsd:enumeration value="ArtifactListViewType"></xsd:enumeration>
			<xsd:enumeration value="ArtifactPrintViewType"></xsd:enumeration>
			<xsd:enumeration value="ArtifactModificationsViewType"></xsd:enumeration>
			<xsd:enumeration value="ArtifactCommentsViewType"></xsd:enumeration>
			<xsd:enumeration value="AccessRightsViewType"></xsd:enumeration>
			<xsd:enumeration value="ArtifactCustomFormViewType"></xsd:enumeration>
			<xsd:enumeration value="EditableTextViewType"></xsd:enumeration>
			<xsd:enumeration value="RelatedArtifactsViewType"></xsd:enumeration>
			<xsd:enumeration value="ListQueryViewType"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="BaseTypeName">
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="Document"></xsd:enumeration>
			<xsd:enumeration value="List"></xsd:enumeration>
			<xsd:enumeration value="InfoPage"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="WebUICommandDefinition">
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="type" type="CommandTypeName" use="required"></xsd:attribute>
		<xsd:attribute name="customPrefix" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="actionStatement" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="description" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:complexType>

	<xsd:simpleType name="CommandTypeName">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CustomCommand"></xsd:enumeration>
			<xsd:enumeration value="PrintActiveDocumentCommand"></xsd:enumeration>
			<xsd:enumeration value="CloseActiveDocumentCommand"></xsd:enumeration>
			<xsd:enumeration value="OpenDocumentSelectedInListCommand"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="SortOrder">
		<xsd:restriction base="xsd:token">
			<xsd:enumeration value="asc"></xsd:enumeration>
			<xsd:enumeration value="desc"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<!-- ArtifactTypeListDefinition End -->

	<xsd:complexType name="AccessRightsList">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="accessRight" type="AccessRightDefinition" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="AccessRightDefinition">
		<xsd:attribute name="partyRoleType" type="xsd:token" />
		<xsd:attribute name="canRead" type="xsd:boolean" />
		<xsd:attribute name="canCreate" type="xsd:boolean" />
		<xsd:attribute name="canModify" type="xsd:boolean" />
		<xsd:attribute name="canDelete" type="xsd:boolean" />
	</xsd:complexType>

</xsd:schema>

=== ZsZs/ProcessPuzzleFramework/Implementation/DomainTier/ObjectTests/com/processpuzzle/sharedfixtures/domaintier/LightWeightBusinessDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<businessDefinition 
	xmlns = "http://www.processpuzzle.com/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.processpuzzle.com/ ../../business/definition/domain/BusinessDefinition.xsd ">

	<!-- PartyTypes: Defines acceptable types of parties. -->
	<partyTypes>
	</partyTypes>
	
	<!-- PartyRoleTypes: Defines the roles can be filled in the workflows. -->
	<partyRoleTypes>
	</partyRoleTypes>
	
	<partyRelationshipTypes>
	</partyRelationshipTypes>
	
	<artifactTypes>
		<artifactTypeGroup name="SystemAdministration">
			<defaultAccessRights>
				<accessRight partyRoleType="Coach" canCreate="true" canDelete="true" canModify="true" canRead="true" />
				<accessRight partyRoleType="XPTeamMember" canCreate="true" canDelete="false" canModify="true" canRead="true" />
			</defaultAccessRights>
		
			<artifactType name="RootArtifactFolder" artifactClassName="com.processpuzzle.artifact.domain.RootArtifactFolder" createOnStartUp="false" group="SystemAdministration" isSingleton="true" isSystem="true" isVersionControlled="false" pessimisticLock="false" refreshOnDocumentActivation="true" refreshOnViewActivation="true">
				<description>Root of all other artifact folders.</description>
				<caption>Root Folder</caption>
				<baseUri>baseUri</baseUri>
				<defaultAccessRights>
					<accessRight partyRoleType="ProcessPuzzleAdministrator" canCreate="false" canDelete="false" canModify="false" canRead="true" />
				</defaultAccessRights>
				<creationProperties>
					<creationProperty name="aProperty" type="string">
						<value>A property value</value>
					</creationProperty>
				</creationProperties>
				<availableViews>
					<propertyViewType name="PropertyView" clientType="NativeView" isDefault="true" isStatic="false" presentationUri="uri" viewClassName="com.processpuzzle.artifact.domain.RootArtifactFolder_PropertyView">
						<viewCaption>Property View</viewCaption>
						<viewAccessUrl>viewAccessUrl</viewAccessUrl>
						<associatedMenuItems>
						</associatedMenuItems>
					</propertyViewType>
				</availableViews>
				<associatedMenuItems></associatedMenuItems>
			</artifactType>
			
			<artifactType name="ArtifactFolder" artifactClassName="com.processpuzzle.artifact.domain.ArtifactFolder" createOnStartUp="false" group="SystemAdministration" isSingleton="false" isSystem="true" isVersionControlled="false" pessimisticLock="false" refreshOnDocumentActivation="true" refreshOnViewActivation="true">
				<description>Describes a folder of artifacts.</description>
				<caption>Artifact Folder</caption>
				<baseUri>baseUri</baseUri>
				<defaultAccessRights>
					<accessRight partyRoleType="ProcessPuzzleAdministrator" canCreate="false" canDelete="false" canModify="false" canRead="true" />
				</defaultAccessRights>
				<creationProperties>
					<creationProperty name="aProperty" type="string">
						<value>A property value</value>
					</creationProperty>
				</creationProperties>
				<availableViews>
					<propertyViewType name="PropertyView" clientType="NativeView" isDefault="true" isStatic="false" presentationUri="uri" viewClassName="com.processpuzzle.artifact.domain.ArtifactFolder_PropertyView">
						<viewCaption>Property View</viewCaption>
						<viewAccessUrl>viewAccessUrl</viewAccessUrl>
						<associatedMenuItems>
							<menuItem name="Print">
								<command name="PrintFolderProperties" description="" type="CustomCommand" actionStatement="" customPrefix="" />
							</menuItem>
						</associatedMenuItems>
					</propertyViewType>
				</availableViews>
				<associatedMenuItems>
					<menuItem name="Activate">
						<command name="ActivateProductCatalog" description="" type="CustomCommand" actionStatement="" customPrefix="" />
					</menuItem>
				</associatedMenuItems>
			</artifactType>

			<artifactType name="UserList"
				artifactClassName="com.processpuzzle.party.artifact.UserList"
				createOnStartUp="true" group="SystemAdministration" isSingleton="true"
				isSystem="true" isVersionControlled="false" pessimisticLock="false"
				refreshOnDocumentActivation="true" refreshOnViewActivation="true">
				<description></description>
				<caption>userList</caption>
				<baseUri>../../../../</baseUri>
				<defaultAccessRights>
					<accessRight partyRoleType="ProcessPuzzleAdministrator"
						canCreate="false" canDelete="false" canModify="false" canRead="true" />
				</defaultAccessRights>
				<creationProperties>
					<creationProperty name="aProperty" type="string">
						<defaultValue></defaultValue>
					</creationProperty>
				</creationProperties>
				<availableViews>
					<artifactListViewType name="ListView"
						clientType="BrowseView" isDefault="true" isStatic="false"
						presentationUri="/Commons/BusinessImplementation/SystemAdministration/UserList_ListView.jsp"
						viewClassName="com.processpuzzle.party.artifact.UserList_ListView"
						listedArtifactType="com.processpuzzle.party.artifact.UserDataSheet"
						orderBy="name" order="desc">
						<viewCaption>ui.viewCaption.list</viewCaption>
						<viewAccessUrl>./CommandControllerServlet?action=ShowListView&amp;artifactName=UserList&amp;viewName=UserList_ListView</viewAccessUrl>
						<associatedMenuItems>
							<menuItem name="Show">
								<command name="ShowUser" description="" type="CustomCommand" actionStatement="" customPrefix="" />
							</menuItem>
						</associatedMenuItems>
					</artifactListViewType>
					<printViewType 
						name="PrintView" 
						clientType="PrintView" 
						isDefault="false" 
						isStatic="false" 
						presentationUri="uri" 
						xmlToFoXsltPath=""
						viewClassName="com.processpuzzle.party.artifact.UserList_PrintView">
						<viewCaption>ui.viewCaption.print</viewCaption>
						<viewAccessUrl></viewAccessUrl>
						<associatedMenuItems>
							<menuItem name="Print">
								<command name="PrintUsers" description="" type="CustomCommand" actionStatement="" customPrefix="" />
							</menuItem>
						</associatedMenuItems>
					</printViewType>
					<artifactCommentsViewType 
						name="Comments" 
						clientType="EditableHtmlView">
						<viewCaption>ui.viewCaption.comments</viewCaption>
						<viewAccessUrl>./CommandControllerServlet?action=ShowDocumentNotes&amp;artifactName=UserList</viewAccessUrl>
					</artifactCommentsViewType>
				</availableViews>
				<associatedMenuItems>
					<menuItem name="Activate">
						<command name="ActivateProductCatalog" description="" type="CustomCommand" actionStatement="" customPrefix="" />
					</menuItem>
				</associatedMenuItems>
			</artifactType>
	
			<artifactType 
				name="UserDataSheet" 
				group="SystemAdministration" 
				artifactClassName="com.processpuzzle.party.artifact.UserDataSheet" 
				domainClassName="com.processpuzzle.application.security.domain.User"
				createOnStartUp="false" 
				isSingleton="false" 
				isSystem="false" 
				isVersionControlled="false"
				pessimisticLock="false">
				<caption>userDataSheet</caption>
				<baseUri>../../../../</baseUri>
				<creationProperties>
					<creationProperty name="userName" type="string" />
					<creationProperty name="password" type="string" />
				</creationProperties>
				<availableViews>
					<propertyViewType 
						name="Properties" 
						presentationUri="/Commons/BusinessImplementation/SystemAdministration/UserDataSheet_PropertyView.jsp" 
						clientType="PropertyView"
						viewClassName="com.processpuzzle.party.artifact.UserDataSheet_PropertyView">
						<viewCaption>ui.viewCaption.properties</viewCaption>
						<viewAccessUrl>./CommandControllerServlet?action=ShowView&amp;artifactName=UserDataSheet&amp;viewName=UserDataSheet_PropertyView</viewAccessUrl>
					</propertyViewType>
					<artifactCustomFormViewType 
						name="BaseData" 
						clientType="CustomFormView" 
						presentationUri="/Commons/BusinessImplementation/SystemAdministration/UserDataSheet_BaseData.jsp" 
						isDefault="true"
						viewClassName="com.processpuzzle.party.artifact.UserDataSheet_BaseData">
						<viewCaption>ui.viewCaption.baseData</viewCaption>
						<viewAccessUrl>./CommandControllerServlet?action=ShowView&amp;artifactName=UserDataSheet&amp;viewName=UserDataSheet_BaseData</viewAccessUrl>
					</artifactCustomFormViewType>
 					<relatedArtifactsViewType 
 						name="RelatedArtifacts" 
 						clientType="CustomFormView" 
 						presentationUri="/BusinessImplementation/ProjectAdministration/Artifact_RelatedArtifacts.jsp"
						viewClassName="com.processpuzzle.artifact.domain.RelatedArtifactsListView">
						<viewCaption>ui.viewCaption.relatedArtifacts</viewCaption>
						<viewAccessUrl>./CommandControllerServlet?action=ShowView&amp;viewName=RelatedArtifactsListView</viewAccessUrl>
					</relatedArtifactsViewType>
					<artifactCommentsViewType name="Comments" clientType="EditableHtmlView">
						<viewCaption>ui.viewCaption.comments</viewCaption>
						<viewAccessUrl>./CommandControllerServlet?action=ShowDocumentNotes</viewAccessUrl>
					</artifactCommentsViewType>
					<accessRightsViewType 
						name="AccessRights" 
						clientType="CustomFormView" 
						presentationUri="/Commons/BusinessImplementation/ProjectAdministration/Artifact_AccessRights.jsp" 
						viewClassName="com.processpuzzle.artifact.domain.AccessRightsView">
						<viewCaption>ui.viewCaption.accessRights</viewCaption>
						<viewAccessUrl>./CommandControllerServlet?action=ShowView&amp;viewName=AccessRightsView</viewAccessUrl>
					</accessRightsViewType>
				</availableViews>
			</artifactType>

		</artifactTypeGroup>

	</artifactTypes>

</businessDefinition>

=== ZsZs/ProcessPuzzleFramework/Implementation/DomainTier/ObjectTests/com/processpuzzle/sharedfixtures/domaintier/AnotherBusinessDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<businessDefinition 
	xmlns = "http://www.processpuzzle.com/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.processpuzzle.com/ ../../business/definition/domain/BusinessDefinition.xsd ">

	<!-- PartyTypes: Defines acceptable types of parties. -->
	<partyTypes>
		<partyType name = "NonProfitOrganization" />
	</partyTypes>
	
	<!-- PartyRoleTypes: Defines the roles can be filled in the workflows. -->
	<partyRoleTypes>
		<partyRoleType name="Customer">
		</partyRoleType>
		
		<partyRoleType name="Vendor">
		</partyRoleType>		
	</partyRoleTypes>
	
	<partyRelationshipTypes>
		<partyRelationshipType name="Sales">
			<partyRelationshipConstraints>
				<partyRelationshipConstraint clientRoleType="Customer" supplierRoleType="Vendor" />
			</partyRelationshipConstraints>
		</partyRelationshipType>
	</partyRelationshipTypes>
	 
</businessDefinition>
