=== ZsZs/ProcessPuzzleFramework/Implementation/DomainTier/Source/com/processpuzzle/party/artifact/Company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	targetNamespace = "http://www.processpuzzle.com/"
	elementFormDefault="qualified"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://www.processpuzzle.com/">

  <xsd:element name="dataroot">
    <xsd:complexType>
      <xsd:sequence minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="company" type="CompanyDef"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
 
  <xsd:complexType name="CompanyDef">
   <xsd:sequence minOccurs="1" maxOccurs="1">
     <xsd:element name="shortName" type="xsd:string"/>
     <xsd:element name="longName" type="xsd:string"/>
     <xsd:element name="address1_UsedFor" type="xsd:string" minOccurs="0"/>
     <xsd:element name="address1_Land" type="xsd:string"/>
     <xsd:element name="address1_ZipCode" type="xsd:string"/>
     <xsd:element name="address1_Settlement" type="xsd:string"/>
     <xsd:element name="address1_Street" type="xsd:string"/>
     <xsd:element name="address1_BuildingNumber" type="xsd:string" minOccurs="0"/>
     <xsd:element name="phone1_CountryCode" type="xsd:string" minOccurs="0"/>
     <xsd:element name="phone1_AreaCode" type="xsd:string" minOccurs="0"/>
     <xsd:element name="phone1_Number" type="xsd:string" minOccurs="0"/>
     <xsd:element name="emailAddress1" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address2_UsedFor" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address2_Land" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address2_ZipCode" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address2_Settlement" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address2_Street" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address2_BuildingNumber" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="phone2_CountryCode" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="phone2_AreaCode" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="phone2_Number" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="emailAddress2" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address3_UsedFor" type="xsd:string" minOccurs="0"></xsd:element>
      <xsd:element name="address3_Land" type="xsd:string" minOccurs="0"></xsd:element>
      <xsd:element name="address3_ZipCode" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address3_Settlement" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address3_Street" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="address3_BuildingNumber" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="phone3_CountryCode" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="phone3_AreaCode" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="phone3_Number" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="emailAddress3" type="xsd:string" minOccurs="0"></xsd:element>
     <xsd:element name="webAddress" type="xsd:string" minOccurs="0"></xsd:element>
    </xsd:sequence>
 </xsd:complexType>
</xsd:schema>

=== ZsZs/ProcessPuzzleFramework/Implementation/DomainTier/ObjectTests/com/processpuzzle/party/artifact/TestCompany.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot 
	xmlns = "http://www.processpuzzle.com/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.processpuzzle.com/ ../Company.xsd">
	
<company>
<shortName>Energometall Kft.</shortName>
<longName>Energometall Kft.</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>8756</address1_ZipCode>
<address1_Settlement>Nagyrécse</address1_Settlement>
<address1_Street>Napfény utca</address1_Street>
<address1_BuildingNumber>1.</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
<phone1_AreaCode>42</phone1_AreaCode>
<phone1_Number>389 849</phone1_Number>
<emailAddress1>balazs.tihanyi@energometall.hu</emailAddress1>
<address2_UsedFor></address2_UsedFor>
<address2_Land></address2_Land>
<address2_ZipCode></address2_ZipCode>
<address2_Settlement></address2_Settlement>
<address2_Street></address2_Street>
<address2_BuildingNumber></address2_BuildingNumber>
<phone2_CountryCode></phone2_CountryCode>
<phone2_AreaCode></phone2_AreaCode>
<phone2_Number></phone2_Number>
<emailAddress2></emailAddress2>
<address3_UsedFor></address3_UsedFor>
<address3_Land></address3_Land>
<address3_ZipCode></address3_ZipCode>
<address3_Settlement></address3_Settlement>
<address3_Street></address3_Street>
<address3_BuildingNumber></address3_BuildingNumber>
<phone3_CountryCode></phone3_CountryCode>
<phone3_AreaCode></phone3_AreaCode>
<phone3_Number></phone3_Number>
<webAddress></webAddress>
</company>
<company>
<shortName>VE ABTROLL</shortName>
<longName>ABT ROLL Kft.</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>4405</address1_ZipCode>
<address1_Settlement>Nyíregyháza</address1_Settlement>
<address1_Street>Debreceni u.</address1_Street>
<address1_BuildingNumber>148.</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
<phone1_AreaCode>42</phone1_AreaCode>
<phone1_Number>450 146</phone1_Number>
<emailAddress1>info@abtroll.hu</emailAddress1>
<address2_UsedFor>szállítási cím</address2_UsedFor>
<address2_Land>Magyarország</address2_Land>
<address2_ZipCode>4405</address2_ZipCode>
<address2_Settlement>Nyíregyháza</address2_Settlement>
<address2_Street>Debreceni u.</address2_Street>
<address2_BuildingNumber>148.</address2_BuildingNumber>
<phone2_CountryCode></phone2_CountryCode>
<phone2_AreaCode></phone2_AreaCode>
<phone2_Number></phone2_Number>
<emailAddress2></emailAddress2>
<address3_UsedFor>fax</address3_UsedFor>
<address3_Land></address3_Land>
<address3_ZipCode></address3_ZipCode>
<address3_Settlement></address3_Settlement>
<address3_Street></address3_Street>
<address3_BuildingNumber></address3_BuildingNumber>
<phone3_CountryCode>36</phone3_CountryCode>
<phone3_AreaCode>42</phone3_AreaCode>
<phone3_Number>450 004</phone3_Number>
<webAddress>www.abtroll.hu</webAddress>
</company>
<company>
<shortName>VE ACCEL</shortName>
<longName>Accell Hunland Kft.</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>5091</address1_ZipCode>
<address1_Settlement>Tószeg</address1_Settlement>
<address1_Street>Parkoló tér</address1_Street>
<address1_BuildingNumber>1.</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
<phone1_AreaCode>56</phone1_AreaCode>
<phone1_Number>586 481</phone1_Number>
<address2_UsedFor>szállítási cím</address2_UsedFor>
<address2_Land>Magyarország</address2_Land>
<address2_ZipCode>5091</address2_ZipCode>
<address2_Settlement>Tószeg</address2_Settlement>
<address2_Street>Parkoló tér</address2_Street>
<address2_BuildingNumber>1.</address2_BuildingNumber>
<phone2_CountryCode></phone2_CountryCode>
<phone2_AreaCode></phone2_AreaCode>
<phone2_Number></phone2_Number>
<emailAddress2></emailAddress2>
<address3_UsedFor>fax</address3_UsedFor>
<address3_Land></address3_Land>
<address3_ZipCode></address3_ZipCode>
<address3_Settlement></address3_Settlement>
<address3_Street></address3_Street>
<address3_BuildingNumber></address3_BuildingNumber>
<phone3_CountryCode></phone3_CountryCode>
</company>
<company>
<shortName>VE AEROSPARES</shortName>
<longName>Aerospares Kft.</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>1171</address1_ZipCode>
<address1_Settlement>Budapest</address1_Settlement>
<address1_Street>Nyitány u.</address1_Street>
<address1_BuildingNumber>56</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
<phone1_AreaCode>1</phone1_AreaCode>
<phone1_Number>257 6600</phone1_Number>
<emailAddress1>reka@aerospares.hu</emailAddress1>
<address2_UsedFor>szállítási cím</address2_UsedFor>
<address2_Land>Magyarország</address2_Land>
<address2_ZipCode>1171</address2_ZipCode>
<address2_Settlement>Budapest</address2_Settlement>
<address2_Street>Nyitány u.</address2_Street>
<address2_BuildingNumber>56</address2_BuildingNumber>
<phone2_CountryCode></phone2_CountryCode>
<phone2_AreaCode></phone2_AreaCode>
<phone2_Number></phone2_Number>
<emailAddress2></emailAddress2>
<address3_UsedFor>fax</address3_UsedFor>
<address3_Land></address3_Land>
<address3_ZipCode></address3_ZipCode>
<address3_Settlement></address3_Settlement>
<address3_Street></address3_Street>
<address3_BuildingNumber></address3_BuildingNumber>
<phone3_CountryCode>36</phone3_CountryCode>
<phone3_AreaCode>1</phone3_AreaCode>
<phone3_Number>256 8840</phone3_Number>
</company>
<company>
<shortName>VE AERZEN</shortName>
<longName>Aerzen Hungaria Kft</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>1036</address1_ZipCode>
<address1_Settlement>Budapest</address1_Settlement>
<address1_Street>Bécsi út</address1_Street>
<address1_BuildingNumber>52.</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
<phone1_AreaCode>1</phone1_AreaCode>
<phone1_Number>439 2200</phone1_Number>
<emailAddress1>info@aerzenhungaria.hu</emailAddress1>
<address2_UsedFor>szállítási cím</address2_UsedFor>
<address2_Land>Magyarország</address2_Land>
<address2_ZipCode>1036</address2_ZipCode>
<address2_Settlement>Budapest</address2_Settlement>
<address2_Street>Bécsi út</address2_Street>
<address2_BuildingNumber>52. III./4.</address2_BuildingNumber>
<phone2_CountryCode></phone2_CountryCode>
<phone2_AreaCode></phone2_AreaCode>
<phone2_Number></phone2_Number>
<emailAddress2></emailAddress2>
<address3_UsedFor>fax</address3_UsedFor>
<address3_Land></address3_Land>
<address3_ZipCode></address3_ZipCode>
<address3_Settlement></address3_Settlement>
<address3_Street></address3_Street>
<address3_BuildingNumber></address3_BuildingNumber>
<phone3_CountryCode>36</phone3_CountryCode>
<phone3_AreaCode>1</phone3_AreaCode>
<phone3_Number>439 1922</phone3_Number>
</company>
<company>
<shortName>VE ÁÉSÁ</shortName>
<longName>Á és Á Kereskedelmi és Szolgáltató Bt.</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>2100</address1_ZipCode>
<address1_Settlement>Gödöllő</address1_Settlement>
<address1_Street>Kossuth L. utca</address1_Street>
<address1_BuildingNumber>6.</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
<phone1_AreaCode>28</phone1_AreaCode>
<phone1_Number>422 884</phone1_Number>
<emailAddress1>profi_szerszam@invitel.hu</emailAddress1>
<address2_UsedFor>szállítási cím</address2_UsedFor>
<address2_Land>Magyarország</address2_Land>
<address2_ZipCode>2100</address2_ZipCode>
<address2_Settlement>Gödöllő</address2_Settlement>
<address2_Street>Kossuth L. utca</address2_Street>
<address2_BuildingNumber>6.</address2_BuildingNumber>
<phone2_CountryCode></phone2_CountryCode>
<phone2_AreaCode></phone2_AreaCode>
<phone2_Number></phone2_Number>
<emailAddress2></emailAddress2>
<address3_UsedFor>fax</address3_UsedFor>
<address3_Land></address3_Land>
<address3_ZipCode></address3_ZipCode>
<address3_Settlement></address3_Settlement>
<address3_Street></address3_Street>
<address3_BuildingNumber></address3_BuildingNumber>
<phone3_CountryCode>36</phone3_CountryCode>
<phone3_AreaCode>28</phone3_AreaCode>
<phone3_Number>422 884</phone3_Number>
</company>
<company>
<shortName>VE AFT</shortName>
<longName>AFT-Európa Kft.</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>2651</address1_ZipCode>
<address1_Settlement>Rétság</address1_Settlement>
<address1_Street>Ipari Park</address1_Street>
<address1_BuildingNumber>5.</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
<phone1_AreaCode>35</phone1_AreaCode>
<phone1_Number>551 000</phone1_Number>
<address2_UsedFor>szállítási cím</address2_UsedFor>
<address2_Land>Magyarország</address2_Land>
<address2_ZipCode>2651</address2_ZipCode>
<address2_Settlement>Rétság</address2_Settlement>
<address2_Street>Ipari Park</address2_Street>
<address2_BuildingNumber>5.</address2_BuildingNumber>
<phone2_CountryCode></phone2_CountryCode>
<phone2_AreaCode></phone2_AreaCode>
<phone2_Number></phone2_Number>
<emailAddress2></emailAddress2>
<address3_UsedFor>fax</address3_UsedFor>
<address3_Land></address3_Land>
<address3_ZipCode></address3_ZipCode>
<address3_Settlement></address3_Settlement>
<address3_Street></address3_Street>
<address3_BuildingNumber></address3_BuildingNumber>
<phone3_CountryCode>36</phone3_CountryCode>
<phone3_AreaCode>35</phone3_AreaCode>
<phone3_Number>551 090</phone3_Number>
</company>
<company>
<shortName>VE ÁGOSTON</shortName>
<longName>Ágoston Tibor egyéni vállalkozó</longName>
<address1_UsedFor>levelezési cím</address1_UsedFor>
<address1_Land>Magyarország</address1_Land>
<address1_ZipCode>8800</address1_ZipCode>
<address1_Settlement>Nagykanizsa</address1_Settlement>
<address1_Street>Miklósfa u.</address1_Street>
<address1_BuildingNumber>85</address1_BuildingNumber>
<phone1_CountryCode>36</phone1_CountryCode>
